### ISSUE TITLE
❓ [Question] How do you install torch-tensorrt (Import error. no libvinfer_plugin.so.8 file error)? 

### ISSUE THREAD

**Issue by YOONAHLEE** [pytorch/TensorRT#1203]
###  ImportError: libnvinfer_plugin.so.8: cannot open shared object file: No such file or directory

cuda and cudnn is installed well.
I installed pytorch and nvidia-tensorrt well in conda environment  
and then install torch-tensorrt via pip

```
pip3 install torch-tensorrt -f https://github.com/pytorch/TensorRT/releases
```
but when I import torch-tensorrt, it gives importError 
ImportError: libnvinfer_plugin.so.8: cannot open shared object file: No such file or directory
```
>>> import torch_tensorrt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user_name/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch_tensorrt/__init__.py", line 11, in <module>
    from torch_tensorrt._compile import *
  File "/home/user_name/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch_tensorrt/_compile.py", line 2, in <module>
    from torch_tensorrt import _enums
  File "/home/user_name/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch_tensorrt/_enums.py", line 1, in <module>
    from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
ImportError: libnvinfer_plugin.so.8: cannot open shared object file: No such file or directory
```

## What you have already tried

```
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
8
>>> torch.cuda.current_device()
0
>>> torch.cuda.get_device_name(0)
'NVIDIA RTX A5000'
>>> torch.__version__
'1.12.0'
>>> import tensorrt
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.12
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda
 - Build command you used (if compiling from source):

 - Are you using local sources or building from archives: 
 - Python version: 3.9.7
 - CUDA version: 11.4
 - GPU models and configuration: NVIDIA RTX A5000
 - Any other relevant information:

**Comment by YOONAHLEE** [comment]
I followed this(https://github.com/pytorch/TensorRT/issues/1026#issuecomment-1119561746)
 and fixed the problem

**Comment by scaler2017** [comment]
I encountered this problem because the version of tensorrt is 10.0.1, I fixed the problem，pip install tensorrt==8.6.1
