### ISSUE TITLE
🐛 [Bug] Unable to import Torch-TensorRT

### ISSUE THREAD

**Issue by valeriosofi** [pytorch/TensorRT#1214]
##  Bug Description
Hello, I was trying to install and import Torch-TensorRT in a colab notebook, but after following all the steps when I import torch_tensorrt I get the following error: 
`ImportError: libnvinfer_plugin.so.8: cannot open shared object file: No such file or directory`
In some other issues was suggested to import tensorrt before importing torch_tensorrt, but even in this case I get an error:
`ImportError: /usr/local/lib/python3.7/dist-packages/torch_tensorrt/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev`
How can I solve this? I also tried on an aws machine and got the same issue.
I can share the notebook where the issue can be easily reproduced: https://colab.research.google.com/drive/1tHRq8Sbe-kE-UoQ4mNlI_IEyDAOoW2sK?usp=sharing

## To Reproduce

1. Start a colab environment with gpu
2. Install pytorch 1.11: pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
3. Install tensorrt: pip install --upgrade nvidia-tensorrt
4. Install pytorch-tensorrt: pip install torch-tensorrt -f https://github.com/pytorch/TensorRT/releases

## Environment

 - Torch-TensorRT Version: 1.1.0
 - PyTorch Version: 1.11
 - How you installed PyTorch: pip
 - Python version: 3.7
 - CUDA version: 11.2
 - GPU models and configuration: Tesla P100

**Comment by RolandGao** [comment]
I have the same problem

**Comment by narendasan** [comment]
This issue is solved in Torch-TensorRT 1.2. 

Adding the following to install Torch-TRT from our CI should give you a build to try out.

I did notice that CoLab is still on CUDA 11.2 so not sure if you will run into issues re: CUDA incompatibility

**Comment by valeriosofi** [comment]
Thank you @narendasan, I tried with that wheel and it works even on colab! Do you have wheels like that also for python 3.8 and 3.9?

**Comment by narendasan** [comment]
Yes you can pull from here: https://app.circleci.com/pipelines/github/pytorch/TensorRT/464/workflows/a07892ac-38f6-4ac9-9d48-69bbc0ce3acb/jobs/1396/artifacts

**Comment by valeriosofi** [comment]
Thank you @narendasan, for now I'll definitely use those links, looking forward for release 1.2 to be officially out!

**Comment by dathudeptrai** [comment]
@narendasan can you share me the torch-tensorrt-1.2.0a0 whl file ?, the link above didn't work anymore
