### ISSUE TITLE
🐛 [Bug] Compilation for CUDA 11.6

### ISSUE THREAD

**Issue by collinmccarthy** [pytorch/TensorRT#1463]
##  Bug Description

After following the instructions for a tarball-based installation, I got the following error:

```
ERROR: /home/cmccarth/.cache/bazel/_bazel_cmccarth/d44a4c69ad518517007c9e3ccc1381ff/external/cuda/BUILD.bazel:12:11 SolibSymlink _solib_k8/_U@cuda_S_S_Ccudart___Ulib64/libcudart.so failed: 1 input file(s) do not exist
```

The file exists at `/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudart.so`, which was installed via apt (`cuda-toolkit-11-6` meta package) on Ubuntu 20.04. For CUDA 11.7, the file is under the `lib64` sub-directory.

When I look at `third_party/cuda/BUILD` I see 

```
cc_library(
    name = "cudart",
    srcs = select({
...
        "//conditions:default": [
            "lib64/libcudart.so",
        ],
```

So I had to change the BUILD file to use `lib` instead of `lib64` everywhere to get it to compile for CUDA 11.6. This could be unique to my setup, but I don't think it is since I'm using the normal apt installation for Ubuntu.

**Comment by collinmccarthy** [comment]
It looks like I'm still having issues, probably because I'm using incompatible versions. When I try to import torch_tensorrt I get:

```
/home/cmccarth/.conda/envs/sparse_act/lib/python3.10/site-packages/torch_tensorrt/lib/libtorchtrt.so: undefined symbol: _ZN2at4_ops4view4callERKNS_6TensorEN3c108ArrayRefIlEE
```

I'm trying to use my local CUDA 11.6 installation and build the python wheel from source. It builds fine with the following package versions:
```
torch                     1.13.0.dev20220921+cu116          pypi_0    pypi
torch-tensorrt            1.3.0a0+a1498ea7          pypi_0    pypi
torchvision               0.14.0.dev20220921+cu116          pypi_0    pypi
```

In the WORKSPACE file I'm using the same tarballs (just downloaded locally): TensorRT-8.4.3.1, CuDNN 8.4.1, LibTorch 1.13.0.dev20220921.

What versions of TensorRT, cuDNN, Torch / LibTorch should I be using to get this to compile (for both Python and C++)?

**Comment by collinmccarthy** [comment]
I'm not sure what the issue was, but I got latest this morning and choose the newest torch 1.13 nightly and it worked.
```
torch                     1.13.0.dev20221003+cu116          pypi_0    pypi
torch-tensorrt            1.3.0a0+0471f2d2          pypi_0    pypi
torchvision               0.14.0.dev20221003+cu116          pypi_0    pypi
```

The WORKSPACE file needs to be updated since the versions in there (from 9/21/22) are no longer available. But I see you're releasing updates for CUDA 11.7 / TRT 8.5 soon so I assume everything will be "fixed" when that gets merged.

**Comment by peri044** [comment]
>> The WORKSPACE file needs to be updated since the versions in there (from 9/21/22) are no longer available. But I see you're releasing updates for CUDA 11.7 / TRT 8.5 soon so I assume everything will be "fixed" when that gets merged.

Yes, we are in the process of landing this PR https://github.com/pytorch/TensorRT/pull/1477 so this should be resolved.

**Comment by dvando** [comment]
> I'm not sure what the issue was, but I got latest this morning and choose the newest torch 1.13 nightly and it worked. It could have easily been my mistake, but I can confirm the following libraries are compatible:
> 
> ```
> torch                     1.13.0.dev20221003+cu116          pypi_0    pypi
> torch-tensorrt            1.3.0a0+0471f2d2          pypi_0    pypi
> torchvision               0.14.0.dev20221003+cu116          pypi_0    pypi
> ```
Hi, where did you get torch-tensorrt v1.3? I couldn't find one. Thank you in advance.

**Comment by collinmccarthy** [comment]
Hi @dvando, that version is from [this commit](https://github.com/pytorch/TensorRT/commit/0471f2d2aae00638149b2b53447af3ed95327e58). Just FYI if you get latest today the WORKSPACE file has been updated to use torch 1.14dev0, so you may just want to switch to that.

**Comment by peri044** [comment]
1.3 is released with support for CUDA-11.7. However, I don't think there would be any specific code changes to support CUDA-11.6. @collinmccarthy  You can try with configuring cuda-11.6 in the WORKSPACE files and try compiling it.

**Comment by peri044** [comment]
Please try 1.3 release and re-open if this is still an issue
